<?php

declare(strict_types=1);

/**
 * @file
 * Provides a prize entity type.
 */

use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function db_prize_theme(): array {
  return [
    'prize' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for prize templates.
 *
 * Default template: prize.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the prize information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_prize(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function db_prize_user_cancel($edit, UserInterface $account, $method): void {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish prizes.
      $storage = \Drupal::entityTypeManager()->getStorage('prize');
      $prize_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($prize_ids) as $prize) {
        $prize->set('status', FALSE)->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize prizes.
      $storage = \Drupal::entityTypeManager()->getStorage('prize');
      $prize_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($prize_ids) as $prize) {
        $prize->setOwnerId(0)->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function db_prize_user_predelete(UserInterface $account): void {
  // Delete prizes that belong to this account.
  $storage = \Drupal::entityTypeManager()->getStorage('prize');
  $prize_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  $storage->delete(
    $storage->loadMultiple($prize_ids)
  );
}
